config/routes.rb
Rails.application.routes.draw do

  root 'search#index'

  post 'results' => 'search#results'

end

app/models/twitter_api.rb
require 'twitter'

class TwitterApi
  def initialize
    configkeys = YAML.load_file("#{Rails.root.to_s}/config/keys.yml")['twitter']
    @client = Twitter::REST::Client.new do |config|
      config.consumer_key        = configkeys['consumer_key']
      config.consumer_secret     = configkeys['consumer_secret']
      config.access_token        = configkeys['access_token']
      config.access_token_secret = configkeys['access_token_secret']
    end
  end

  def search(term)
    @client.search(term, result_type: "recent").take(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def results
    query = params['query']
    tw_api = TwitterApi.new
    session[:search_history] ||= []
    results = tw_api.search(query)
    @result_texts = results.collect(&:text)
    session[:search_history] << [query, DateTime.current, @result_texts]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweetomator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/search/_form.html.slim
= form_tag(results_path) do
  = label_tag(:query) do
    |Search for:
  = text_field_tag(:query)
  = submit_tag(:search)

app/views/search/_format_results.html.slim
- result_texts.each do |result_text|
  .result
    = result_text

app/views/search/_search_history.html.slim
- if session[:search_history].present?
  h3 Search History:
  - session[:search_history].each do |search_term, search_date, results|
    h4
      |Search term was: #{search_term}
    h4
      |Search date: #{search_date}
    h4 Results were:
    = render('format_results', result_texts: results)

app/views/search/index.html.slim
h1 Tweetometer

= render('form')

= render('search_history')

app/views/search/results.html.slim
|Search again:
= render('form')

h2 Search results

= render('format_results', result_texts: @result_texts)

= render('search_history')